# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3902b4b99b3bde0ac857d297ef6f38e649976feff95e8730fd59a8dffc261db868884f441e88d46491c31345c3379bf734c2832ad064fcbf38fc6e60436176

test:
  secret_key_base: 4ac9e711c31f1f910a208c4b7e2b439db4e47c6d289cbb29bd9d3a289cce6a04f0f6aca721c9961ccfcb460a29ccaf9fd55597f39fefef0381c2df88bedc6351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
